### PR TITLE
[tools] Avoid scanning of images that cannot be exported by docker

### LINKED ISSUE #5020: [ci] Fix CVE scanner
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.46.0

### Expected Behavior

CVE report every week

### Actual Behavior

Errors in pipelines, no reports
https://github.com/deckhouse/deckhouse/actions/workflows/cve-weekly.yml

### Steps To Reproduce

_No response_

### Additional Information

Let's try to migrate as much logic as possible from github to makefile / scripts

### Logs

_No response_

### PR DESCRIPTION
**Pull request by mvasl**
## Description

Added a check if docker can export an image before attempting to scan it with `trivy`.

## Why do we need it, and what problem does it solve?

Fixes #5020

## Changelog entries

```changes
section: tools
type: chore
summary: fixed weekly CVE scans
impact_level: low
```

### CODE REVIEW

File: tools/cve/base-images.sh [hunk 1]
```diff
@@ -71,6 +71,12 @@ function __main__() {
   htmlReportHeader > out/base-images.html
 
   for image in $BASE_IMAGES; do
+    # Some of our base images contain no layers.
+    # Trivy cannot scan such images because docker never implemented exporting them.
+    # We should not attempt to scan images that cannot be exported.
+    # Fixes https://github.com/deckhouse/deckhouse/issues/5020
+    docker save $(sed -E 's/(@sha256.*)$//g;t' <<< $image) &> /dev/null || continue
```
Comment (RomanenkoDenys) [inline tools/cve/base-images.sh:78]:
```suggestion
    docker manifest inspect $image | jq -e '.layers | length > 0' > /dev/null || continue
```

**Review by RomanenkoDenys — CHANGES_REQUESTED** [review]
docker save generates traffic

**Review by RomanenkoDenys — APPROVED** [review]
LGTM
