### PR TITLE
[deckhouse] fix initial module config validation

### LINKED ISSUE #12198: [deckhouse] applying an initial invalid module config causes deckhouse crashloopback
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.67+

### Expected Behavior

Applying initial invalid module config does not cause deckhouse crashloopback, the error should be placed in module config status and module config is ignored.

### Actual Behavior

Applying initial invalid module config causes crashloopback because the validation openapi spec not loaded yet. 

### Steps To Reproduce

1. Create an invalid module config for not installed module
2. Apply it

### Additional Information

_No response_

### Logs

```shell
"level": "error",
    "msg": "Fatal: init module manager: load initial config for KubeConfigManager: 3 errors occurred:\n\t* observabilityPlatform.general.tls.ca must be of type string: \"object\"\n\t* observabilityPlatform.general.tls.ca.key is a forbidden property\n\t* observabilityPlatform.general.tls.ca.crt is a forbidden property\n\n",
    "stacktrace": [
```

### PR DESCRIPTION
**Pull request by ipaqsa**
## Description
It provides initial module config validation.

## Why do we need it, and what problem does it solve?
Fixes #12198

1. Create an invalid module config before module discovered.

2. Check that mr not deployed
```
root@dev-master-0:~# k get mr
NAME                    PHASE        UPDATE POLICY   TRANSITIONTIME   MESSAGE
echo-v0.7.111           Deployed     alpha-auto      18d              
echo-v0.7.24            Superseded                   18d              
operator-ceph-v1.0.15   Deployed     deckhouse       76d              
test-v0.11.3            Pending      alpha-auto      81m              initial module config validation failed: validate module: test.option is a forbidden property
```

3. Check module`s status(it is stuck in Downloading):
```
root@dev-master-0:~# k get module test
NAME   WEIGHT   SOURCE   PHASE         ENABLED   READY
test            test     Downloading   False     False
```

5. Clear wrong params and check mr:
```
root@dev-master-0:~# k get mr
NAME                    PHASE        UPDATE POLICY   TRANSITIONTIME   MESSAGE
echo-v0.7.111           Deployed     alpha-auto      19d              
echo-v0.7.24            Superseded                   19d              
operator-ceph-v1.0.15   Deployed     deckhouse       76d              
test-v0.11.3            Deployed     alpha-auto      154m            
```

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse
type: fix
summary: Add initial module config validation.
```

### CODE REVIEW

File: deckhouse-controller/pkg/controller/confighandler/handler.go [hunk 1]
```diff
@@ -37,14 +36,12 @@ var _ backend.ConfigHandler = &Handler{}
 
 type Handler struct {
 	client            client.Client
-	log               *log.Logger
```
Comment (yalosev) [inline deckhouse-controller/pkg/controller/confighandler/handler.go:40]: why? :)

Comment (ipaqsa) [reply deckhouse-controller/pkg/controller/confighandler/handler.go:40]: Useless

**Review by yalosev — APPROVED** [review]

**Review by ldmonster — APPROVED** [review]
