### PR TITLE
[node-manager] Add alert about unavailable CAPS instances

### LINKED ISSUE #8649: [monitoring] There is no alert in prometheus-rules about a failure when creating a static node of cluster with CAPS.
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

When maintaining nodes in a static instance of some namespace, there is a possibility that the node introduction into the cluster will fail. For the monitoring such events, prometheus-rules does not have the necessary alerts.

### Proposed Solution

Adding special alerts for clusters with CAPS.

### Additional Information

There is a "NodeGroupReplicasUnavailable" alert for a cloud cluster, which is triggered when there is no possibility of creating a new node. A similar alert is needed, only for a static cluster with a static cloud provider API.

### PR DESCRIPTION
**Pull request by sprait**
## Description

Add alert about unavailable CAPS instances.

## Why do we need it, and what problem does it solve?

Closes #8649 .

## What is the expected result?

1. Add new node-group for caps without  prepared StaticInstance:
```bash
[root@dev-master-0 ~]# kubectl apply -f - <<EOF
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: caps-system
spec:
  nodeType: Static
  staticInstances:
    count: 1
    labelSelector:
      matchLabels:
        role: caps-system
EOF
nodegroup.deckhouse.io/caps-system created

[root@dev-master-0 ~]# kubectl get staticinstances.deckhouse.io  -l role=caps-system
No resources found
```
2.   Check instance in the cluster and the relevant alert about its state in prometheus:

```bash
[root@dev-master-0 ~]# kubectl get instance -l node.deckhouse.io/group=caps-system
NAME                      STATUS    AGE
caps-system-g9lc6-645tv   Pending   5m
```

image

## Checklist
- [x] The code is covered by unit tests.
- [x] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: node-manager
type: feature
summary: Add alert about unavailable CAPS instances.
impact_level: default
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/static'...

File: modules/040-node-manager/hooks/machine_deployments_caps_metrics.go [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+}
+
+var _ = sdk.RegisterFunc(&go_hook.HookConfig{
+	Queue: "/modules/node-manager/metrics",
+	Kubernetes: []go_hook.KubernetesConfig{
+		{
+			Name:                   "machinedeployment_status",
+			ApiVersion:             "cluster.x-k8s.io/v1beta1",
+			Kind:                   "MachineDeployment",
+			WaitForSynchronization: pointer.Bool(false),
```
Comment (name212) [inline modules/040-node-manager/hooks/machine_deployments_caps_metrics.go:55]: We can have hybrid cluster (for example zVirt with static instances) and we will have alert not only with CAPS instances and zVirt machine deployments.

Better way: add additional label here https://github.com/deckhouse/deckhouse/blob/eb1bc03155dd862149b2f8e93d39a6f7e3464461/modules/040-node-manager/templates/node-group/_capi_machine_deployment.tpl#L21-L20
and filter by this label

**Review by name212 — CHANGES_REQUESTED** [review]
one thing

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vcd'...

**Comment by sprait** [comment]
/e2e/abort static;Static;containerd;1.27 10402349783 10402349783-1-con-1-27 /sys/deckhouse-oss/install:pr9195 astra@192.168.199.187

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've started the workflow for label 'e2e/run/vcd'...

**Comment by sprait** [comment]
/e2e/abort yandex-cloud;WithoutNAT;containerd;1.27 10405340080 10405340080-1-con-1-27 /sys/deckhouse-oss/install:pr9195 redos@89.169.150.232

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @sprait. I've recognized your '/e2e/abort' command and started the workflow...

File: modules/040-node-manager/hooks/machine_deployments_caps_metrics.go (hunk 1 above)
Comment (name212) [reply modules/040-node-manager/hooks/machine_deployments_caps_metrics.go:56]: I just clarified one thing and it looks like adding a label will result in a machine deployment rollout https://cluster-api.sigs.k8s.io/developer/architecture/controllers/machine-deployment#in-place-propagation
Sorry for the wrong tip. Let's add an annotation, subscribe to all MachineDeployments and filter by annotation.

**Review by name212 — CHANGES_REQUESTED** [review]
one thing

File: modules/040-node-manager/hooks/machine_deployments_caps_metrics.go (hunk 1 above)
Comment (sprait) [reply modules/040-node-manager/hooks/machine_deployments_caps_metrics.go:56]: I've checked that adding a label in the machinedeployment doesn't trigger a rollout in the machineset/machine or nodes. Perhaps this documentation page is incomplete.

**Review by name212 — APPROVED** [review]

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @z9r5. I've started the workflow for label 'e2e/run/yandex-cloud'...
