### PR TITLE
[nginx-ignress] fix proxy-failover-iptables

### LINKED ISSUE #4943: [nginx-ingress] refactor proxy-failover-iptables app
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.46

### Expected Behavior

no restarts when 127.0.0.1:10254/healthz is unavailable
no flooding in ingress-failover iptables chain

### Actual Behavior

* The app shouldn't panic in case 127.0.0.1:10254/healthz handle is unavailable (http.resp == nil)
* The app's working logic should be reconsidered - it keeps adding duplicate entries to the host iptables on restart
```
-A ingress-failover -m socket --nowildcard -j RETURN
-A ingress-failover -p tcp -j CONNMARK --set-xmark 0x3/0xffffffff
-A ingress-failover -p tcp -j CONNMARK --set-xmark 0x3/0xffffffff
-A ingress-failover -j CONNMARK --save-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A ingress-failover -p tcp -j DNAT --to-destination 169.254.20.11:81
-A ingress-failover -p tcp -j DNAT --to-destination 169.254.20.11:444
-A ingress-failover -m socket --nowildcard -j RETURN
-A ingress-failover -p tcp -j CONNMARK --set-xmark 0x3/0xffffffff
-A ingress-failover -p tcp -j CONNMARK --set-xmark 0x3/0xffffffff
-A ingress-failover -j CONNMARK --save-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A ingress-failover -p tcp -j DNAT --to-destination 169.254.20.11:81
-A ingress-failover -p tcp -j DNAT --to-destination 169.254.20.11:444
-A ingress-failover -m socket --nowildcard -j RETURN
-A ingress-failover -p tcp -j CONNMARK --set-xmark 0x3/0xffffffff
-A ingress-failover -p tcp -j CONNMARK --set-xmark 0x3/0xffffffff
-A ingress-failover -j CONNMARK --save-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A ingress-failover -p tcp -j DNAT --to-destination 169.254.20.11:81
-A ingress-failover -p tcp -j DNAT --to-destination 169.254.20.11:444
```

### Steps To Reproduce

1. use HostWithFailover inlet for an nginx ingress controller
2. somehow prevent main controller pod from starting
3. check restarts in the proxy-failover pod and check the host's iptables (ingress-failover chain) after a few restarts

### Additional Information

_No response_

### Logs

```shell
root@dev-master-0:~# kubectl  logs -n d8-ingress-nginx proxy-main-failover-xfgkc iptables-loop -p
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x669065]

goroutine 1 [running]:
main.loop(0xc00019ff48?)
	/src/main.go:136 +0x65
main.main()
	/src/main.go:126 +0x7af
```
```

### PR DESCRIPTION
**Pull request by miklezzzz**
## Description
Proxy-failover-iptables app crashes and duplicates iptables rules on start up.

## Why do we need it, and what problem does it solve?
Close #4943 

## What is the expected result?
The app isn't panicking if http://127.0.0.1:10254/healthz isn't available.
No duplicates in the ingress-failover iptables chain.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: nginx-ingress
type: fix
summary: Fix proxy-failover-iptables panicking and iptables rules duplicating.
impact_level: default
```

### CODE REVIEW

**Review by yalosev — APPROVED** [review]

File: modules/402-ingress-nginx/images/proxy-failover-iptables/main.go [hunk 1]
```diff
@@ -133,16 +134,22 @@ func main() {
 
 func loop(iptablesMgr *iptables.IPTables) error {
 	resp, err := http.Get("http://127.0.0.1:10254/healthz")
-	defer resp.Body.Close()
+
+	if resp != nil {
```
Comment (nabokihms) [inline modules/402-ingress-nginx/images/proxy-failover-iptables/main.go:138]: NIT: We usually change the order. If the error is nil, the respo body is always not nil. Thus, it is safe to do:

```go
if err != nil {
  log.Println(err)
  return iptablesMgr.DeleteIfExists("nat", chainName, socketExistsRule...)
}

defer resp.Body.Close()

if resp.StatusCode != http.StatusOK {
  log.Printf("Got %d status code", resp.StatusCode)
  return iptablesMgr.DeleteIfExists("nat", chainName, socketExistsRule...)
}
```

Comment (miklezzzz) [reply modules/402-ingress-nginx/images/proxy-failover-iptables/main.go]: fixed.
p.s. sorry, didn't notice your comment and pushed with some extra force :-|

**Comment by deckhouse-BOaTswain** [comment]
Cherry pick PR [4965](https://github.com/deckhouse/deckhouse/pull/4965) to the branch [release-1.46](https://github.com/deckhouse/deckhouse/tree/release-1.46) successful!
