### PR TITLE
[dhctl] Some improvements and fixes

### LINKED ISSUE #1200: [dhctl] In some cases start ssh connection is freezing and does not report any errors with private keys
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.29.0

### Expected Behavior

Report all errors about starting ssh connection.

### Actual Behavior

Dhctl does not report starting ssh connection errors.

### Steps To Reproduce

_No response_

### Additional Information

Some times when we pass incorrect ssh key via comandline ssh does not exit with `Permission denied (publickey)`, server suggest enter user password. Dhctl is freezing at moment and did not notify about somthing.
It confuse users.

What do we need to fix it?

Add `-oPasswordAuthentication=no` and/or add -`oBatchMode=yes` parameter(s) when ssh running via dhctl.

Maybe we need more research about ssh command looking for another cases, which can freeze connection.

### Logs

_No response_

### LINKED ISSUE #1202: [dhctl] Make flexible for checks control-plane nodes in converge operation
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Use case. Why is this important?

In some cases deckhouse pod is not ready but you need to converge control-plane nodes.
We can give confirmations for "waiting readiness deckhouse pod", "control-plane-manager readiness check", "ssh available checks", "k8s node readiness check" operations to user. 

### Proposed Solution

Do it :-) 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by name212**
Signed-off-by: Nikolay Mitrofanov <nikolay.mitrofanov@flant.com>

## Description
Add `-o PasswordAuthentication=no` parameter to ssh command to prevent waiting enter password when user pass incorrect ssh key

Add confirmation for waiting Deckhouse controller readiness and control-plane node readiness.

Do not output Deckhouse logs when getting node group cloud config for created node groups.  

## Why do we need it, and what problem does it solve?
Close #1202
Close #1200

## Changelog entries

```changes
section: dhctl 
type: feature
summary: Add confirmation for waiting Deckhouse controller readiness and control-plane node readiness.
```

```changes
section: dhctl 
type: fix
summary: Exclude password authentication check while connecting to host
```

### CODE REVIEW

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @name212. I've started the workflow for label 'e2e/run/openstack'...

File: dhctl/pkg/kubernetes/actions/converge/converge.go [hunk 1]
```diff
@@ -355,7 +367,8 @@ func (c *NodeGroupController) Run() error {
 	replicas := getReplicasByNodeGroupName(c.config, nodeGroupName)
 	step := getStepByNodeGroupName(nodeGroupName)
 
-	nodeCloudConfig, err := GetCloudConfig(c.client, nodeGroupName)
+	const notShowDeckhouseLogs = false
+	nodeCloudConfig, err := GetCloudConfig(c.client, nodeGroupName, notShowDeckhouseLogs)
```
Comment (diafour) [inline dhctl/pkg/kubernetes/actions/converge/converge.go:371]:
```suggestion
	nodeCloudConfig, err := GetCloudConfig(c.client, nodeGroupName, HideDeckhouseLogs)
```

File: dhctl/pkg/kubernetes/actions/converge/converge.go [hunk 2]
```diff
@@ -233,7 +233,8 @@ func (r *Runner) createPreviouslyNotExistedNodeGroup(group config.TerraNodeGroup
 			return err
 		}
 
-		nodeCloudConfig, err := GetCloudConfig(r.kubeCl, group.Name)
+		const showDeckhouseLogs = true
+		nodeCloudConfig, err := GetCloudConfig(r.kubeCl, group.Name, showDeckhouseLogs)
```
Comment (diafour) [inline dhctl/pkg/kubernetes/actions/converge/converge.go:237]:
```suggestion
		nodeCloudConfig, err := GetCloudConfig(r.kubeCl, group.Name, ShowDeckhouseLogs)
```

File: dhctl/pkg/operations/converge/infra/hook/controlplane/hook.go [hunk 3]
```diff
@@ -178,16 +180,56 @@ func (h *Hook) AfterAction() error {
...
 func (h *Hook) IsReady() error {
 	excludeNode := h.nodeToConverge
 	if !h.runAfterAction {
 		excludeNode = ""
 	}
 
-	err := deckhouse.WaitForReadinessNotOnNode(h.kubeCl, excludeNode)
-	if err != nil {
-		return err
+	if h.runConfirm("Do you want to wait Deckhouse controller will be ready?") {
```
Comment (diafour) [inline dhctl/pkg/operations/converge/infra/hook/controlplane/hook.go:227]:
```suggestion
	if h.runConfirm("Wait until Deckhouse controller is ready?") {
```

File: dhctl/pkg/operations/bootstrap.go [hunk 4]
```diff
@@ -379,7 +380,8 @@ func GetBastionHostFromCache() (string, error) {
 
 func BootstrapAdditionalMasterNodes(kubeCl *client.KubernetesClient, metaConfig *config.MetaConfig, addressTracker map[string]string) error {
 	return log.Process("bootstrap", "Create master NodeGroup", func() error {
-		masterCloudConfig, err := converge.GetCloudConfig(kubeCl, converge.MasterNodeGroupName)
+		const showDeckhouseLogs = true
+		masterCloudConfig, err := converge.GetCloudConfig(kubeCl, converge.MasterNodeGroupName, showDeckhouseLogs)
```
Comment (name212) [inline dhctl/pkg/operations/bootstrap.go:384]:
```suggestion
		masterCloudConfig, err := converge.GetCloudConfig(kubeCl, converge.MasterNodeGroupName, ShowDeckhouseLogs)
```

**Review by nabokihms — APPROVED** [review]
