### PR TITLE
[dhctl] Use the `errors.As` function to handle errors

### LINKED ISSUE #8356: [dhctl] There isn't error message for failed detect_bundle script
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.58.10

### Expected Behavior

dhtcl bootstrap have to show the error messages from detect_bundle.sh.

### Actual Behavior

Trying to install d8 to Debian 12 powered VM. It isn't supported by d8 in this release, but the messages from dhctl bootstrap aren't informative:
```shell
[deckhouse] root@30781928e0f5 / # dhctl bootstrap ...
...
┌ ⛵ ~ Bootstrap: Detect Bashible Bundle
└ ⛵ ~ Bootstrap: Detect Bashible Bundle (3.83 seconds) FAILED

timeout while "Get bundle": last error: detect_bundle.sh: execute on remote: exit status 1
```

### Steps To Reproduce

_No response_

### Additional Information

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by artbin**
## Description

Use the `errors.As` function to handle errors.

## Why do we need it, and what problem does it solve?

An error can be wrapped in another error, and we need to unwrap it to get the original error. The `errors.As` function helps us to do that. It unwraps the error and checks if it is of the specified type.

Close #8356.

## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: dhctl
type: fix
summary: Fix incorrect error handling.
impact_level: default
```

### CODE REVIEW

**Review by aleksey-su — APPROVED** [review]

**Review by name212 — APPROVED** [review]

File: dhctl/pkg/system/ssh/frontend/upload-script.go [hunk 1]
```diff
@@ -106,6 +107,13 @@ func (u *UploadScript) Execute() (stdout []byte, err error) {
 
 	err = scriptCmd.Run()
 	if err != nil {
+		var exitErr *exec.ExitError
+		if errors.As(err, &exitErr) {
+			// Stderr holds a subset of the standard error output from the Cmd.Output method
+			// but we do not call this method
+			exitErr.Stderr = cmd.StderrBytes()
```
Comment (mvasl) [inline dhctl/pkg/system/ssh/frontend/upload-script.go:114]: Can you explain more clearly why this is required exactly? This comment does not provide enough context to me.

Comment (artbin) [reply dhctl/pkg/system/ssh/frontend/upload-script.go]: Added a more detailed comment.

**Review by mvasl — APPROVED** [review]
