### PR TITLE
[tools] Change image for init container for deckhouse deployment with change-registry.sh 

### LINKED ISSUE #4056: [tools] change-registry.sh script not changing image for external modules init container
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.44.1

### Expected Behavior

When use change-registry.sh script, it must change image for init container for deckhouse deployment

### Actual Behavior

Now it isn't change image for init container for deckhouse deployment

### Steps To Reproduce

_No response_

### Additional Information

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by alex123012**
## Description

When using change-registry.sh script now, it doesn't change image for init container for deckhouse deployment. THis PR fixes this
## Why do we need it, and what problem does it solve?

fix #4056
## Checklist
- [ ] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: tools
type: fix
summary: change-registry.sh script changes deckhouse initContainer image 
impact_level: low
```

### CODE REVIEW

**Review by name212 — APPROVED** [review]

File: tools/change-registry.sh [hunk 1]
```diff
@@ -87,6 +88,11 @@ function parse_args() {
   REGISTRY_SCHEME="$(sed "s/:\/\///" <<< "$REGISTRY_SCHEME")"
   DECKHOUSE_TAG="$(kubectl -n d8-system get deploy deckhouse -o json | jq '.spec.template.spec.containers[] | select(.name=="deckhouse") | .image | split(":")[-1]' -r)"
 
+  tmp_external_modules_tag="$(kubectl -n d8-system get deploy deckhouse -o json | jq '.spec.template.spec.initContainers[] | select(.name=="init-external-modules") | .image | split(":")[-1]' -r 2>/dev/null)"
+  if [[ "$tmp_external_modules_tag" != "" ]]; then
+    DECKHOUSE_EXTERNAL_MODULES_IMAGE_TAG="${tmp_external_modules_tag}"
```
Comment (RomanenkoDenys) [inline tools/change-registry.sh:93]: i think it will be DECKHOUSE_INIT_EXTERNAL_MODULES_CONTAINER

**Review by RomanenkoDenys — CHANGES_REQUESTED** [review]
some nits

File: tools/change-registry.sh (hunk 1 above)
Comment (alex123012) [reply tools/change-registry.sh:93]: Maybe it would be better if we make it like the deckhouse image var name on line 89? something like `DECKHOUSE_INIT_EXTERNAL_MODULES_CONTAINER _TAG`?

**Review by RomanenkoDenys — APPROVED** [review]

**Review by name212 — APPROVED** [review]
