### PR TITLE
[deckhouse] Deckhouse pod readiness probe during the release minor update

### LINKED ISSUE #7644: [deckhouse] Deckhouse pod readiness probe during the release minor update
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1.58.0

### Expected Behavior

Deckhouse should not update until controller is ready

### Actual Behavior

Deckhouse can update anytime because of internal restart (during the modules install)
You can find more details [here](https://flant.slack.com/archives/C78AQG5EY/p1708969595896869?thread_ts=1708956613.973419&cid=C78AQG5EY)

### Steps To Reproduce

_No response_

### Additional Information

Instead of checking that [deckhouse pod](https://github.com/deckhouse/deckhouse/blob/v1.58.0/modules/002-deckhouse/hooks/update_deckhouse_image.go#L122) is ready, we can make an http request like `curl http://10.222.206.133:8080/readyz` and analyze the http response code - 200/500.
Then we will not be dependent on readiness probe and will have the actual state of the controller's queue

### Logs

_No response_

### PR DESCRIPTION
**Pull request by Dmitrykob**
## Description

The mechanism for checking if the pods are ready has been replaced. Now used the pod readiness probe via http.
get http://{{deckhouse pod ip addr}}:9650/readyz

screen-1

## Why do we need it, and what problem does it solve?

close #7644

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: deckhouse
type: fix
summary: pod readiness probe during the release minor update
impact_level: default
```

### CODE REVIEW

File: modules/002-deckhouse/hooks/update_deckhouse_image.go [hunk 1]
```diff
@@ -462,3 +459,21 @@ func getDeckhousePods(snap []go_hook.FilterResult) ([]deckhousePodInfo, error) {
 
 	return deckhousePods, nil
 }
+
+func isDeckhousePodReady(dc dependency.Container) bool {
+	deckhousePodIP := os.Getenv("ADDON_OPERATOR_LISTEN_ADDRESS")
+
+	httpClient := dc.GetHTTPClient()
+	url := fmt.Sprintf("http://%s:9650/readyz", deckhousePodIP)
```
Comment (yalosev) [inline modules/002-deckhouse/hooks/update_deckhouse_image.go:467]: I assume we can use `127.0.0.1` here

File: modules/002-deckhouse/hooks/update_deckhouse_image.go [hunk 2]
```diff
@@ -462,3 +459,21 @@ func getDeckhousePods(snap []go_hook.FilterResult) ([]deckhousePodInfo, error) {
 
 	return deckhousePods, nil
 }
+
+func isDeckhousePodReady(dc dependency.Container) bool {
```
Comment (yalosev) [inline modules/002-deckhouse/hooks/update_deckhouse_image.go:463]: We can pass only http client here

**Comment by deckhouse-BOaTswain** [comment]
Failure: cherry-pick commit 086dd666dc5de749d6cf268f9f2644ba5d18c1d3 to the branch [release-1.58](https://github.com/deckhouse/deckhouse/tree/release-1.58) failed. See [Job](https://github.com/deckhouse/deckhouse/actions/runs/8372644091) for details.
