### PR TITLE
[prometheus] Fix AlertmanagerConfig Heml template

### LINKED ISSUE #3369: Creating two CustomAlertmanager failed
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/deckhouse/deckhouse/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/deckhouse/deckhouse/issues) for an issue that matches the one I want to file, without success.

### Version

v1-41-2   Deployed

### Expected Behavior

When created two CustomAlertmanager, created two alertmanager sts and two configs.

### Actual Behavior

When created two CustomAlertmanager, something deletes one of Alertmanagerconfig, and prometheus operator fails: msg="Sync \"d8-monitoring/alerts-to-alerta\" failed: provision alertmanager configuration: failed to get global AlertmanagerConfig: alertmanagerconfigs.monitoring.coreos.com \"alerts-to-alerta\" not found"
kubectl get CustomAlertmanager
NAME               TYPE
alerts-to-alerta   External
alerts-to-telega   Internal
$kubectl get Alertmanagerconfig -A
NAMESPACE       NAME               AGE
d8-monitoring   alerts-to-telega   17m

### Steps To Reproduce

Create this objects:
1.
apiVersion: deckhouse.io/v1alpha1
kind: CustomAlertmanager
metadata:
  name: alerts-to-alerta
spec:
  internal:
    receivers:
    - name: alerta-webhook-reciever
      webhookConfigs:
      - sendResolved: true
        url: http://alerta.d8-monitoring.svc:8080/webhooks/prometheus
    route:
      groupBy:
      - job
      groupInterval: 1m
      groupWait: 30s
      receiver: alerta-webhook-reciever
      repeatInterval: 1m
  type: External
2. 
apiVersion: deckhouse.io/v1alpha1
kind: CustomAlertmanager
metadata:
  name: alerts-to-telega
spec:
  internal:
    receivers:
    - name: webhook-telega-reciever
      webhookConfigs:
      - sendResolved: true
        url: http://telegram-alertmanager.d8-monitoring.svc:8080/alerts
    route:
      groupBy:
      - job
      groupInterval: 5m
      groupWait: 30s
      receiver: webhook-telega-reciever
      repeatInterval: 3h
  type: Internal

### Additional Information

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by artbin**
## Description

Add three dashes `---` to separate resources in alertmanagerconfig.yaml Helm template. Add tests.

## Why do we need it, and what problem does it solve?

In Helm templates you MUST separate resources with three dashes `---`.
Close #3369 

## What is the expected result?

Fixed creation of multiple CustomAlertmanager resources.

## Checklist
- [x] The code is covered by unit tests.
- [ ] e2e tests passed.
- [ ] Documentation updated according to the changes.
- [x] Changes were tested in the Kubernetes cluster manually.

## Changelog entries

```changes
section: prometheus
type: fix
summary: Fixed creation of multiple CustomAlertmanager resources.
impact_level: default
```

### CODE REVIEW

File: modules/300-prometheus/template_tests/multiple_custom_alert_managers_test.go [hunk 1]
```diff
@@ -0,0 +1,198 @@
+/*
+Copyright 2021 Flant JSC
```
Comment (name212) [inline modules/300-prometheus/template_tests/multiple_custom_alert_managers_test.go:2]: Please fix to 2023 year

**Review by name212 — CHANGES_REQUESTED** [review]
One thing

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Comment by deckhouse-BOaTswain** [comment]
Aye, aye, @artbin. I've started the workflow for label 'e2e/run/openstack'...

**Review by name212 — APPROVED** [review]
